Fix CI Node JS error
ERROR: npm v9.1.2 is known not to run on Node.js v12.19.1.

You'll need to upgrade to a newer Node.js version in order to use this
version of npm. This version of npm supports the following node
versions: `^14.17.0 || ^16.13.0 || >=18.0.0`.